/**
 * Read helpers for the AI Marketing Studio envelopes.
 *
 * Components never reach into post.ai_studio_output directly — going through
 * these keeps the envelope shape in one place, so bumping
 * STUDIO_SCHEMA_VERSION means fixing these functions and nothing else.
 */

import {
  EMPTY_GENERATION_META,
  STUDIO_OUTPUT_KEYS,
  type AiStudioInput,
  type AiStudioOutput,
  type CampaignPlan,
  type CompetitorAnalysis,
  type ContentVariations,
  type CtaOptions,
  type GenerationMeta,
  type HashtagGroups,
  type ImageAnalysis,
  type PlatformVariations,
  type SeoAnalysis,
  type StudioOutputKey,
} from "./types";

/** Minimal shape these helpers need — avoids a circular import on Post. */
interface StudioBearing {
  ai_studio_input?: AiStudioInput | null;
  ai_studio_output?: AiStudioOutput | null;
}

/** Adds the pre-studio columns, still written by the original Make scenario. */
interface LegacyBearing extends StudioBearing {
  ai_caption?: string | null;
  ai_hashtags?: string[] | null;
  ai_platform_content?: Record<string, string | undefined> | null;
}

export function getStudioInput(post: StudioBearing): AiStudioInput | null {
  return post.ai_studio_input ?? null;
}

export function getStudioOutput(post: StudioBearing): AiStudioOutput | null {
  return post.ai_studio_output ?? null;
}

export function getGenerationMeta(post: StudioBearing): GenerationMeta {
  return post.ai_studio_output?.meta ?? EMPTY_GENERATION_META;
}

/** True when the generation failed outright or only partly succeeded. */
export function hasGenerationError(post: StudioBearing): boolean {
  const status = getGenerationMeta(post).status;
  return status === "failed" || status === "partial";
}

/** Which output sections this post actually has content for. */
export function producedKeys(post: StudioBearing): StudioOutputKey[] {
  const output = post.ai_studio_output;
  if (!output) return [];
  return STUDIO_OUTPUT_KEYS.filter((key) => output[key] != null);
}

/** True when Make wrote back at least one generated section. */
export function hasStudioOutput(post: StudioBearing): boolean {
  return producedKeys(post).length > 0;
}

// ─── Per-section accessors ───────────────────────────────────────────────────

export function getImageAnalysis(post: StudioBearing): ImageAnalysis | null {
  return post.ai_studio_output?.imageAnalysis ?? null;
}

export function getContentVariations(post: StudioBearing): ContentVariations | null {
  return post.ai_studio_output?.contentVariations ?? null;
}

export function getCtaOptions(post: StudioBearing): CtaOptions | null {
  return post.ai_studio_output?.ctaOptions ?? null;
}

export function getHashtagGroups(post: StudioBearing): HashtagGroups | null {
  return post.ai_studio_output?.hashtagGroups ?? null;
}

export function getSeoAnalysis(post: StudioBearing): SeoAnalysis | null {
  return post.ai_studio_output?.seo ?? null;
}

export function getCampaignPlan(post: StudioBearing): CampaignPlan | null {
  return post.ai_studio_output?.campaign ?? null;
}

export function getCompetitorAnalysis(post: StudioBearing): CompetitorAnalysis | null {
  return post.ai_studio_output?.competitor ?? null;
}

export function getPlatformVariations(post: StudioBearing): PlatformVariations | null {
  return post.ai_studio_output?.platformVariations ?? null;
}

// ─── Flattened views, envelope first with a legacy fallback ──────────────────
//
// Surfaces that predate the Marketing Studio (the post editor's AI panel) want
// one caption, one flat tag list and one caption per platform. These read the
// envelope when it's there and fall back to the original columns, so a post
// generated by either pipeline renders the same.

/** Best single caption: the first studio variation, else the legacy caption. */
export function getPrimaryCaption(post: LegacyBearing): string | null {
  const variation = post.ai_studio_output?.contentVariations?.variations?.[0];
  return variation?.caption ?? post.ai_caption ?? null;
}

/**
 * Every hashtag as a flat, de-duplicated list without the leading `#`.
 * Legacy rows sometimes hold one merged string ("tag1, tag2"), so split those.
 */
export function getFlatHashtags(post: LegacyBearing): string[] {
  const groups = post.ai_studio_output?.hashtagGroups?.groups;
  const tags = groups
    ? groups.flatMap((group) => group.hashtags.map((hashtag) => hashtag.tag))
    : (post.ai_hashtags ?? []).flatMap((tag) => tag.split(/[,\s#]+/));
  return [...new Set(tags.map((tag) => tag.replace(/^#/, "")).filter(Boolean))];
}

/** One caption per platform, keyed by platform id. */
export function getPlatformCaptions(post: LegacyBearing): Record<string, string> {
  const variations = post.ai_studio_output?.platformVariations;
  const source = variations
    ? Object.fromEntries(
        Object.entries(variations).map(([platform, v]) => [platform, v.caption]),
      )
    : (post.ai_platform_content ?? {});

  return Object.fromEntries(
    Object.entries(source).filter((entry): entry is [string, string] =>
      Boolean(entry[1]),
    ),
  );
}
