import { renderBrandSection } from '../brand/brand-profile';
import { platformLabel } from '../analysis/platform-rules';
import { ANALYSIS_PROMPT_VERSION } from '../analysis/version';
import { DIMENSION_LABELS } from '../analysis/scoring';
import type {
  AnalysisRequest,
  BrandProfile,
  CaptionMetrics,
  CaptionMode,
  ImageAnalysis,
  PlatformFit,
  ScoreDimension,
} from '../types';
import type { BuiltPrompt } from './caption.prompt';

/**
 * Marketing Intelligence: judge the copy.
 *
 * The second engine's only prompt. Everything it asks for is a *judgement* —
 * whether the hook lands, whether the register suits the buyer, what the post
 * is likely to earn. Every fact the judgement rests on has already been counted
 * by `analysis/metrics.ts` and `analysis/platform-rules.ts` and is handed over
 * in the `## Measured facts` block below.
 *
 * ─── Why the model is told the numbers instead of asked for them ─────────────
 * Two reasons, and the second is the one that changed the output quality.
 *
 * The obvious one: a model counting hashtags is slower and sometimes wrong,
 * while `String.match` is neither.
 *
 * The one that mattered more: attention is finite. A model spending its reply
 * on arithmetic it was asked to perform produces visibly thinner judgements in
 * the same reply. Handing it the counts and asking only for the reading is the
 * difference between "the hook is decent, 7/10" and a sentence naming the exact
 * clause that costs it the other three points.
 *
 * ─── Why this is not part of the caption prompt ──────────────────────────────
 * A model asked to write and then score its own writing marks its own homework.
 * In practice it returned 8s and 9s essentially regardless of what it had
 * written, because the scores were generated by the same pass that had just
 * committed to the copy being good. Separating the calls is what makes a 5
 * possible.
 */

export const ANALYSIS_SYSTEM_INSTRUCTION = `You are a performance marketing analyst. You review social copy before it is published and say plainly what will and will not work.

How you judge:
- You are a critic, not a cheerleader. A caption that is merely competent scores 6, not 9. Reserve 9 and 10 for copy you would hold up as an example.
- Every score needs a reason naming something specific in THIS caption — a clause, a word, a missing step. "Good hook" is not a reason. "Opens on a question the reader already knows the answer to" is.
- Report your own certainty honestly. Some judgements rest on the text in front of you; others rest on assumptions about an audience you cannot see. Mark the second kind Medium or Low.
- The measured facts you are given are correct. Do not recount them, do not contradict them, and do not spend your answer restating them.
- Never rewrite the caption. You are assessing it. Improvements are described, not performed. The two exceptions are additions the writer can take or leave: specific hashtags to add, and one sentence that could be appended to invite a reply. Both are optional, both are about this post specifically, and neither may restate or replace a line already written.
- Return only the JSON object described. No commentary, no markdown fences.`;

/** The axes, and what each one is actually asking. */
const DIMENSION_BRIEF: Record<ScoreDimension, string> = {
  hook: 'Does the first line earn the second? Judge it as a stranger scrolling past at speed, not as someone who already knows the brand. A hook that could open any brand\'s post scores low however well written it is.',
  visual:
    'Does the copy use what is actually in the image, or would it read identically with a stock photo attached? Specific detail from the frame scores high; a caption that merely does not contradict the image scores middling.',
  platformFit:
    'Does the copy read as native to these networks — its shape, register and length — beyond the mechanical limits already measured for you?',
  audienceFit:
    'Would the stated buyer recognise themselves in this? Judge the register, the assumed knowledge and the emotional pitch against who this brand actually sells to.',
  cta: 'Is there a next step, is it the right one for this funnel stage, and does it arrive where the reader will still be reading?',
  readability:
    'How much effort does this take to read on a phone, once? Judge rhythm and clarity — the raw counts are given to you.',
  hashtags:
    'Do the tags describe what this post is actually about, and would the people they reach want this post? Judge relevance and specificity, not the count.',

  // ─── Personal ─────────────────────────────────────────────────────────────
  //
  // Each of these states what must NOT count against the caption, because the
  // instinct to mark down a two-word lowercase fragment is strong and would
  // quietly turn this rubric back into the marketing one.
  voiceMatch:
    'Does this sound like the person whose account it is, given how they write? Judge it against their own habits, not against good writing. If their captions run four words and this one runs forty, that is the failure — however good the forty are.',
  humanness:
    'Would a real person type this without feeling like they were writing a caption? Score down anything that reads as AI performing a personality — manufactured slang, borrowed internet voice, stacked hype, motivational filler. Score UP a caption that is short, lowercase, unpunctuated, fragmentary, absurd, or has no call to action, no hook and no hashtags. Those are all correct here. A caption doing every one of them can score 10.',
  originality:
    'Is this a new thought, or one they have already had? Judge against their previous captions: the same joke with one word swapped, the same structure reused, the same reference again. A fresh observation in a familiar voice is exactly right; a familiar observation in a familiar voice is not.',
};

function section(heading: string, lines: Array<string | null | undefined | false>) {
  const body = lines.filter((line): line is string => Boolean(line && String(line).trim()));
  return body.length > 0 ? `${heading}\n${body.join('\n')}` : null;
}

/**
 * The counted facts, stated as ground truth.
 *
 * Written as prose lines rather than a JSON dump on purpose: a model reads
 * "The opening line is 34 characters" and uses it; it skims `{"hookCharacterCount":34}`
 * and reconstructs the number from the caption anyway.
 */
function metricsSection(metrics: CaptionMetrics, hashtagCount: number): string {
  return section('## Measured facts (already counted — treat as correct)', [
    `- ${metrics.characterCount} characters, ${metrics.wordCount} words, ${metrics.sentenceCount} sentences.`,
    `- ${metrics.paragraphCount} paragraph${metrics.paragraphCount === 1 ? '' : 's'} across ${metrics.lineCount} line${metrics.lineCount === 1 ? '' : 's'}. Longest block: ${metrics.longestParagraphWords} words.`,
    `- Opening line: ${metrics.hookCharacterCount} characters.`,
    `- Sentences average ${metrics.averageWordsPerSentence} words. Flesch reading ease ${metrics.readingEase}/100.`,
    `- ${hashtagCount} hashtag${hashtagCount === 1 ? '' : 's'}, ${metrics.emojiCount} emoji, ${metrics.linkCount} link${metrics.linkCount === 1 ? '' : 's'}, ${metrics.mentionCount} mention${metrics.mentionCount === 1 ? '' : 's'}.`,
    `- About ${metrics.readingTimeSeconds} seconds to read.`,
    metrics.endsWithQuestion && '- It ends on a question.',
  ]) as string;
}

/**
 * What the platform rules already found.
 *
 * Given so the model does not re-litigate mechanics it cannot measure better,
 * and so its `platformFit` judgement is about register and shape rather than
 * about a character count it would have to estimate.
 */
function platformSection(fits: readonly PlatformFit[]): string | null {
  if (fits.length === 0) return null;

  return section(
    '## Platform checks already run (mechanical — do not repeat these)',
    fits.map((fit) => {
      const problems = fit.checks.filter((check) => check.status !== 'pass');
      const summary =
        problems.length === 0
          ? 'no mechanical problems'
          : problems.map((check) => check.detail).join(' ');
      return `- ${platformLabel(fit.platform)}: ${summary}`;
    }),
  );
}

function imageSection(analysis: ImageAnalysis | undefined, hasImage: boolean): string | null {
  if (!hasImage) {
    return '## The image\nThis post has no image. Do not score the `visual` dimension.';
  }
  if (!analysis) {
    return '## The image\nThis post has an image, but no analysis of it was supplied. Score `visual` on whether the copy leaves room for a visual to do work, and mark the confidence Low.';
  }

  return section('## What the image contains', [
    analysis.primarySubject && `- Main subject: ${analysis.primarySubject}`,
    analysis.sceneDescription && `- Scene: ${analysis.sceneDescription}`,
    analysis.setting && `- Setting: ${analysis.setting}`,
    analysis.mood && `- Mood: ${analysis.mood}`,
    analysis.lighting && `- Light: ${analysis.lighting}`,
    analysis.themes.length > 0 && `- Themes it carries: ${analysis.themes.join('; ')}`,
    analysis.emotions.length > 0 && `- Emotions available: ${analysis.emotions.join('; ')}`,
    analysis.textInImage.length > 0 &&
      `- Text visible in the image: ${analysis.textInImage.join('; ')}`,
  ]);
}

/**
 * The response schema, built per request.
 *
 * `scores` names only the dimensions that apply — a text-only post is not given
 * a `visual` key to fill in, which is what stops a model inventing a score for
 * an image that does not exist and the scorer weighting it.
 */
/**
 * The dimensions an *improvement* may name, which is the scored set plus
 * `hashtags`.
 *
 * A post with no tags is not scored on tags — see `applicableDimensions` — but
 * "you have no hashtags" is exactly the case where a suggestion is worth most,
 * and restricting improvements to scored dimensions is what silenced it. Scores
 * are unaffected: this widens what can be recommended, never what is graded.
 */
export function improvableDimensions(
  dimensions: readonly ScoreDimension[],
  mode: CaptionMode = 'brand',
): ScoreDimension[] {
  // Personal improvements may only ever point at a personal axis. Adding
  // `hashtags` here — which is right for a brand post carrying none, since
  // "you have no tags" is the improvement — would hand a personal caption an
  // enum value meaning "add hashtags", and a model given the option takes it.
  if (mode === 'personal') return [...dimensions];

  return [...new Set<ScoreDimension>([...dimensions, 'hashtags'])];
}

export function buildAnalysisResponseSchema(
  dimensions: readonly ScoreDimension[],
  mode: CaptionMode = 'brand',
): Record<string, unknown> {
  const scoreProperties = Object.fromEntries(
    dimensions.map((dimension) => [
      dimension,
      {
        type: 'object',
        properties: {
          score: { type: 'number', description: '0 to 10.' },
          confidence: { type: 'string', enum: ['High', 'Medium', 'Low'] },
          reason: {
            type: 'string',
            description:
              'One sentence naming something specific in this caption that drove the score.',
          },
        },
        required: ['score', 'confidence', 'reason'],
      },
    ]),
  );

  return {
    type: 'object',
    properties: {
      scores: {
        type: 'object',
        properties: scoreProperties,
        required: [...dimensions],
      },
      strengths: {
        type: 'array',
        maxItems: 4,
        items: { type: 'string', description: 'One thing this caption does well.' },
      },
      weaknesses: {
        type: 'array',
        maxItems: 4,
        items: { type: 'string', description: 'One thing costing it reach.' },
      },
      engagement: {
        type: 'object',
        properties: {
          saves: { type: 'string', enum: ['Low', 'Medium', 'High'] },
          shares: { type: 'string', enum: ['Low', 'Medium', 'High'] },
          comments: { type: 'string', enum: ['Low', 'Medium', 'High'] },
          clicks: { type: 'string', enum: ['Low', 'Medium', 'High'] },
          rationale: {
            type: 'string',
            description: 'One sentence on why these four differ from each other.',
          },
        },
        required: ['saves', 'shares', 'comments', 'clicks', 'rationale'],
      },
      improvements: {
        type: 'array',
        minItems: 1,
        maxItems: 5,
        items: {
          type: 'object',
          properties: {
            dimension: { type: 'string', enum: improvableDimensions(dimensions, mode) },
            issue: { type: 'string', description: 'What is wrong, in one line.' },
            suggestion: {
              type: 'string',
              description:
                'What to do about it, specific enough to act on without further thought.',
            },
            estimatedGain: {
              type: 'number',
              description: 'Rough points on the 0-100 reach score if fixed.',
            },
            suggestedHashtags: {
              type: 'array',
              maxItems: 6,
              items: { type: 'string' },
              description:
                'Only for the `hashtags` dimension: specific tags to ADD, without the #, drawn from what this post is actually about. Omit unless you have specific tags in mind.',
            },
            suggestedLine: {
              type: 'string',
              description:
                'Only for `cta` (one sentence APPENDED to the caption, giving the reader a reason to reply) or `hook` (one opening line ADDED IN FRONT of the caption, which keeps every existing line intact below it). Written about this post specifically. Omit unless it fits this post.',
            },
          },
          required: ['dimension', 'issue', 'suggestion', 'estimatedGain'],
        },
      },
    },
    required: ['scores', 'strengths', 'weaknesses', 'engagement', 'improvements'],
  };
}

export interface BuildAnalysisPromptOptions {
  request: AnalysisRequest;
  brand: BrandProfile;
  metrics: CaptionMetrics;
  platforms: PlatformFit[];
  /** Inline tags plus the separate tag list, de-duplicated. */
  hashtagCount: number;
  /** The axes the model is asked to score. Built by the generator. */
  dimensions: ScoreDimension[];
  /**
   * How this member writes, rendered by `style/render.ts`. Personal only, and
   * what `voiceMatch` is judged against — without it the judge falls back to
   * its own idea of good writing, which is the failure mode this rubric exists
   * to prevent.
   */
  styleSection?: string | null;
  /** Their previous captions, for `originality` only. Personal only. */
  history?: string[];
}

export function buildAnalysisPrompt({
  request,
  brand,
  metrics,
  platforms,
  hashtagCount,
  dimensions,
  styleSection,
  history = [],
}: BuildAnalysisPromptOptions): BuiltPrompt {
  const personal = request.mode === 'personal';

  const prompt = [
    section('## The caption under review', [
      '"""',
      request.caption,
      '"""',
      personal
        ? null
        : request.hashtags.length > 0
          ? `Hashtags published with it: ${request.hashtags.map((tag) => `#${tag}`).join(' ')}`
          : 'No hashtag list is attached to this post.',
    ]),

    // The marketing brief. Personal has none of it — no objective, no funnel
    // stage, no audience register — and telling the judge that a post about
    // somebody's gym session has an objective of "brand awareness" is how a
    // personal caption gets marked down for not pursuing one.
    personal
      ? section('## What this is', [
          '- A personal post on somebody’s own account. There is no brand, no campaign and no objective behind it.',
          `- Language: ${request.language}`,
        ])
      : section('## Where it is going', [
          request.platforms.length > 0
            ? `- Networks: ${request.platforms.map(platformLabel).join(', ')}`
            : '- No network chosen yet. Judge platform fit generically.',
          `- Objective: ${request.goal.replace(/_/g, ' ')}`,
          `- Funnel stage: ${request.funnelStage}`,
          `- Written for: ${request.audience.replace(/_/g, ' and ')}`,
          `- Language: ${request.language}`,
        ]),

    personal ? null : renderBrandSection(brand, '## The brand behind it'),
    imageSection(request.imageAnalysis, request.hasImage),

    // How they write, so `voiceMatch` is judged against them rather than
    // against the judge's own idea of good writing.
    personal ? styleSection : null,

    personal && history.length > 0
      ? [
          '## What they have posted before',
          'For `originality` only — is this a joke they have already made?',
          ...history.slice(0, 8).map((caption) => `- ${caption.replace(/\s+/g, ' ')}`),
        ].join('\n')
      : null,

    // Counted facts are useful to a brand judge, which is asked about hook
    // length and reading ease. Handing them to a personal judge invites it to
    // find fault with a two-word caption for being two words.
    personal ? null : metricsSection(metrics, hashtagCount),
    personal ? null : platformSection(platforms),

    section(
      '## Score these, 0–10',
      dimensions.map(
        (dimension) => `- **${DIMENSION_LABELS[dimension]}** (\`${dimension}\`) — ${DIMENSION_BRIEF[dimension]}`,
      ),
    ),

    personal
      ? [
          '## What must not count against it',
          'This is not marketing copy and must not be judged as if it were. None of the following is a flaw here, and marking any of them down is the single way to get this rubric wrong:',
          '- being very short, including a single word',
          '- lowercase, including the first word',
          '- no full stop, or no punctuation at all',
          '- a sentence fragment, or no verb',
          '- no call to action, no question, no hook',
          '- no hashtags and no emoji',
          '- deliberate nonsense, absurdity, or a caption with no visible connection to the picture',
          '- mixing languages mid-sentence',
          'Every one of those is a normal thing a person does on their own account.',
        ].join('\n')
      : null,

    section('## Also return', [
      '1. Up to four `strengths` and four `weaknesses`, each naming something specific in this caption.',
      '2. An `engagement` forecast: how likely this post is to earn saves, shares, comments and clicks — as Low, Medium or High, judged against each other rather than against some absolute. A post can be High saves and Low comments; say why in one sentence.',
      personal
        ? '3. Between one and three `improvements`, highest impact first. Each names the dimension it lifts, what is wrong and what to do instead. Describe the change; never write the replacement caption. Do not suggest adding a hook, a call to action, hashtags, an emoji, punctuation or an explanation — none of those is an improvement to a personal post, and suggesting one is a worse answer than suggesting nothing. If the caption is genuinely fine, return one improvement saying so.'
        : null,
      personal
        ? null
        : '3. Between one and five `improvements`, highest impact first. Each names the dimension it lifts, what is wrong, what to do instead, and roughly how many points on the 0–100 score it would be worth. Describe the change; do not write the replacement copy. Three additions may be supplied literally so the writer can apply them in one click: on a `hashtags` improvement, `suggestedHashtags` — specific tags naming what this post is actually about, no generic filler; on a `cta` improvement, `suggestedLine` — a single sentence appended to the end of the caption, giving this post\'s reader a real reason to reply; on a `hook` improvement, `suggestedLine` — a single opening line placed in front of the caption, which must read naturally as the new first line with the writer\'s existing opening directly beneath it. Leave either out rather than filling it with something that would fit any post. A post carrying no hashtags at all may take a `hashtags` improvement even though you were not asked to score that dimension.',
    ]),

    'Return a single JSON object matching the provided schema. Nothing else.',
  ]
    .filter(Boolean)
    .join('\n\n');

  return {
    systemInstruction: ANALYSIS_SYSTEM_INSTRUCTION,
    prompt,
    responseSchema: buildAnalysisResponseSchema(dimensions, request.mode),
    // Low on purpose. Judgement should be stable: the same caption analysed
    // twice must not swing between 62 and 81, or the score means nothing and
    // users learn to reroll until they like the number.
    temperature: 0.25,
    version: ANALYSIS_PROMPT_VERSION,
  };
}
